language: java
install: true
jdk:
- oraclejdk8
script:
- "./gradlew build"
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    tags: true
env:
  global:
    secure: O0vS0VkbTNmikWAslDvisek/Sq+CjWD5t7znNku7lmyafmEn69aSTeVUtY4+h/xH13r3+aeD61OcsgZ/xKy9t6OGqFqiAZca01B5wey6yG3kvJl3x/nLf/uCC4Fx58nWg+khKnlZSih4xYazEvZ6/mDwWnzCQGxO93la0ml1xpUETXFi+CRHFvcNvP5JV41ESVDEWYslCg4Sn6BzFD77AaHEl7s1efYe1mZm5znsFzc9fn6MtnG7NkDp91CJjwbSrdxAeWl0qVjvViDRk2St+RrsfOq/Dpg3hs947QVT4DGRlch/gfIkFIEmAf9FmdmGo7X/DpBz0zDpw8XEwxcuPrDPvwPiZM11eQ+Vsx/rDbYMr4uBSYfwVJ5n9n94Rd3J5zIJ3rUg1PinXSRD06R51Xk1XyN6xpljZazqFyCLZSY4Hep4FUtu+Ru92co4JbolGp3ttYxWQp3T+LzZTA33j2veJ0GS5oii6S20mEWWCG36ewVKkYw9i8S9ccosXXnAdVELM6I1nVEyZj8YGk/jvxDT+JSRS7r9TZIFVzDl5z1lp7zR+nHRjFy07B2PbVEdaJ41vf8xB+0L9kabjxQdTCrI5pjsQ35MIAEFnD87ZpnD2RnO24WeH1yATQ6FayiPAC52cQmuPXypiQPeG1blA2wib/Lgg2LV9o9Tte0Wt8w=
